# Generated by Django 3.2.16 on 2022-12-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_img', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('step', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('end_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_time', models.DateField(auto_now_add=True, verbose_name='Error Ocurred')),
                ('step', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'log_error',
                'managed': False,
            },
        ),
    ]
